name: 'Get & Cache Dependencies' 
description: 'Get and cache Dependencies'
runs:
    using: 'composite'

    steps:
      
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
        shell: bash
      
      - name: Build website
        run: npm run build
        shell: bash
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: dist